site_name: Insta360 Help & Documents
pages:
- FAQ: 'index.md'    
- Docs:    
    - Complete Guide to Insta360 4K Spherical Camera: 'docs/Complete_Guide_to_Insta360_4K_Spherical_Camera.md'  
    - Guide to Play and Edit 360 Degree Videos: 'docs/Guide_to_Play_and_Edit_Spherical_Videos.md'  
    - Instructions on Insta360 4K Mobile App: 'docs/Instructions_on Insta360_4K_Mobile_App_Insta360_Explorer_and_Insta360_Player.md'  
    - Losslessly Import Raw Video to AE/PR Using This Miraculous Plugin: 'docs/Losslessly_Import_Raw_Material_to_AE_PR_with_Miraculous_Plugin.md'  
    - Pr Tutorial for Insta360 Panaroma: 'docs/Pr_Tutorial_for_Insta360_panorama.md'            
# - Terms：
#  - example: 'example.md'
# - Other:    
#     - Insta360-Player: 'help/insta360_software/insta360Player/releasenotes.md' 
theme_dir: 'insta360_help'
site_favicon: favicon.ico