site_name: Insta360 Help & Documents
pages:
- Help Center:  
  - FAQ: 'index.md'    
- Documents:    
    - 'Nano': 
        - Warranty Policy: 'documents/nano/Warranty_Policy.md'
        - Privacy Policy: 'documents/nano/Privacy_Policy.md'
        - User Service Agreement: 'documents/nano/User_Service_Agreement.md'
        - Pub English : 'documents/nano/Pub_English.md'
    - Complete Guide to Insta360 4K Spherical Camera: 'documents/Complete_Guide_to_Insta360_4K_Spherical_Camera.md'  
    - Guide to Play and Edit 360 Degree Videos: 'documents/Guide_to_Play_and_Edit_Spherical_Videos.md'  
    - Instructions on Insta360 4K Mobile App: 'documents/Instructions_on_Insta360_4K_Mobile_App_Insta360_Explorer_and_Insta360_Player.md'  
    - Losslessly Import Raw Video to AE/PR Using This Miraculous Plugin: 'documents/Losslessly_Import_Raw_Material_to_AE_PR_with_Miraculous_Plugin.md'  
    - Pr Tutorial for Insta360 Panaroma: 'documents/Pr_Tutorial_for_Insta360_panorama.md'      
    - Live Streaming Introduction: 'documents/Live_stream_introduction.md'      
    - Youtube 360 Live Streaming Tutorial: 'documents/Youtube_360_Live_Streaming_Tutorial.md'          
# - Terms：
#  - example: 'example.md'
# - Other:    
#     - Insta360-Player: 'help/insta360_software/insta360Player/releasenotes.md' 
theme_dir: 'insta360_help'
site_favicon: favicon.ico